### ISSUE TITLE
Handling multiple IPs exposed on the same network interfaces

### ISSUE THREAD

**Issue by CensorKoo** [livekit/livekit#602] opened 2022-04-07 16:17 UTC
@davidzhao @boks1971 

I have kept all the logs this time, please check the attachment. Here are some of the errors I've highlighted. The binary I'm running is compiled from the latest source code.

Thanks again to the LiveKit team for providing such a great product.

`
2022-04-07T13:15:15.015+0800	ERROR	livekit	rtc/signalhandler.go:24	could not handle answer	{"room": "random_newl_2_1649308512137", "roomID": "RM_4yvUv4YjLvs6", "participant": "14986346", "pID": "PA_48uPq8yM9kvh", "error": "could not set remote description: InvalidModificationError: invalid proposed signaling state transition: stable->SetRemote(answer)->stable", "errorVerbose": "InvalidModificationError: invalid proposed signaling state transition: stable->SetRemote(answer)->stable\ncould not set remote description\ngithub.com/livekit/livekit-server/pkg/rtc.(*ParticipantImpl).HandleAnswer\n\t/root/livekit-server/pkg/rtc/participant.go:508\ngithub.com/livekit/livekit-server/pkg/rtc.HandleParticipantSignal\n\t/root/livekit-server/pkg/rtc/signalhandler.go:23\ngithub.com/livekit/livekit-server/pkg/service.(*RoomManager).rtcSessionWorker\n\t/root/livekit-server/pkg/service/roommanager.go:424\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1571"}
github.com/livekit/livekit-server/pkg/rtc.HandleParticipantSignal
	/root/livekit-server/pkg/rtc/signalhandler.go:24
github.com/livekit/livekit-server/pkg/service.(*RoomManager).rtcSessionWorker
	/root/livekit-server/pkg/service/roommanager.go:424
2022-04-07T13:15:15.016+0800	INFO	livekit	service/rtcservice.go:225	source closed connection	{"room": "random_newl_2_1649308512137", "participant": "14986346", "connID": "CO_Dyb7KRKVgoHi"}
`

`
2022-04-06T23:10:18.447+0800	ERROR	livekit.mux	mux/mux.go:121	mux: ending readLoop dispatch error io: read/write on closed pipe
	{"room": "random_newl_2_1649257798784", "roomID": "RM_Puc9WfPrKE4n", "participant": "14956419", "pID": "PA_xa4imABDP6uT", "transport": "PUBLISHER"}
github.com/pion/webrtc/v3/internal/mux.(*Mux).readLoop
	/root/godev/pkg/mod/github.com/pion/webrtc/v3@v3.1.27/internal/mux/mux.go:121
`

`2022-04-07T02:17:17.038+0800	ERROR	livekit	logger/logger.go:34	could not add down track	{"participant": "14999873", "pID": "PA_5pDHbgHW2YPi", "error": "DownTrack already exist"}
github.com/livekit/protocol/logger.Errorw
	/root/godev/pkg/mod/github.com/livekit/protocol@v0.13.1-0.20220331092121-f5e8e205306a/logger/logger.go:34
github.com/livekit/livekit-server/pkg/rtc.(*MediaTrackReceiver).AddSubscriber
	/root/livekit-server/pkg/rtc/mediatrackreceiver.go:209
github.com/livekit/livekit-server/pkg/rtc.(*UpTrackManager).AddSubscriber
	/root/livekit-server/pkg/rtc/uptrackmanager.go:126
github.com/livekit/livekit-server/pkg/rtc.(*Room).onTrackPublished
	/root/livekit-server/pkg/rtc/room.go:616
github.com/livekit/livekit-server/pkg/rtc.(*ParticipantImpl).handleTrackPublished
	/root/livekit-server/pkg/rtc/participant.go:1441
github.com/livekit/livekit-server/pkg/rtc.(*ParticipantImpl).mediaTrackReceived
	/root/livekit-server/pkg/rtc/participant.go:1429
github.com/livekit/livekit-server/pkg/rtc.(*ParticipantImpl).onMediaTrack
	/root/livekit-server/pkg/rtc/participant.go:925
`

`2022-04-07T05:04:32.750+0800	ERROR	livekit	rtc/transport.go:358	could not set local description	{"room": "random_newl_2_1649279054705", "roomID": "RM_JDMFLq9Hhmw7", "participant": "14988207", "pID": "PA_seQeypW9vamq", "transport": "SUBSCRIBER", "error": "InvalidStateError: connection closed"}
github.com/livekit/livekit-server/pkg/rtc.(*PCTransport).createAndSendOffer
	/root/livekit-server/pkg/rtc/transport.go:358
github.com/livekit/livekit-server/pkg/rtc.(*PCTransport).CreateAndSendOffer
	/root/livekit-server/pkg/rtc/transport.go:297
github.com/livekit/livekit-server/pkg/rtc.(*PCTransport).Negotiate.func1
	/root/livekit-server/pkg/rtc/transport.go:288
2022-04-07T05:04:32.750+0800	ERROR	livekit	rtc/transport.go:289	could not negotiate	{"room": "random_newl_2_1649279054705", "roomID": "RM_JDMFLq9Hhmw7", "participant": "14988207", "pID": "PA_seQeypW9vamq", "transport": "SUBSCRIBER", "error": "InvalidStateError: connection closed"}
github.com/livekit/livekit-server/pkg/rtc.(*PCTransport).Negotiate.func1
	/root/livekit-server/pkg/rtc/transport.go:289
`

`2022-04-07T06:08:05.528+0800	ERROR	livekit.pc	v3@v3.1.27/peerconnection.go:1582	Incoming unhandled RTP ssrc(2731095130), OnTrack will not be fired. incoming SSRC failed Simulcast probing	{"room": "random_newl_2_1649282864935", "roomID": "RM_embtrPdkqKjF", "participant": "14974334", "pID": "PA_ZRUNQot4VdEd", "transport": "PUBLISHER"}
github.com/pion/webrtc/v3.(*PeerConnection).undeclaredMediaProcessor.func1.1
	/root/godev/pkg/mod/github.com/pion/webrtc/v3@v3.1.27/peerconnection.go:1582
`

`2022-04-07T06:39:35.790+0800	ERROR	livekit.sctp	sctp@v1.8.2/association.go:2427	[0xc002ec9180] retransmission failure: T1-init	{"room": "random_newl_2_1649284430786", "roomID": "RM_wKVjGU9kvq84", "participant": "14732048", "pID": "PA_YpHsJfdx7fTu", "transport": "SUBSCRIBER"}
github.com/pion/sctp.(*Association).onRetransmissionFailure
	/root/godev/pkg/mod/github.com/pion/sctp@v1.8.2/association.go:2427
github.com/pion/sctp.(*rtxTimer).start.func1
	/root/godev/pkg/mod/github.com/pion/sctp@v1.8.2/rtx_timer.go:158
`

`2022-04-07T00:22:52.557+0800	ERROR	livekit	rtc/mediatracksubscriptions.go:407	could not write RTCP	{"room": "random_newl_2_1649262155533", "roomID": "RM_tvXi7pjd2Dtr", "participant": "14994548", "pID": "PA_MUCz9nMyTHgR", "trackID": "TR_VCLqHaSgq2cp7k", "error": "io: read/write on closed pipe"}`

[livekit-server.log.tar.gz](https://github.com/livekit/livekit-server/files/8444785/livekit-server.log.tar.gz)

**Comment by davidzhao** [comment] 2022-04-07 22:26
@CensorKao are you seeing any actual issues? It's expected to have some amount of errors in the complex world of WebRTC networking. Most of the logs here are due to timing of events and should not cause any issues to the end user. They are safe to ignore.

**Comment by CensorKao** [comment] 2022-04-08 16:36
There are a lot of these error messages:
ERROR livekit.pc v3@v3.1.27/peerconnection.go:1582 Incoming unhandled RTP ssrc

I do not know under what scenario will this error reported. The user will not receive the offer and thus the session will fail. Now the problem is that the success rate is low. We have also checked the client logs, and the main reason is that users cannot receive the offer.

@davidzhao 
Sorry for the wrong place. It's hard to have a repreduce step, because suddenly participants will fail to receive offers in a certain period of time. Next we'll take a closer look at the client logs to see if we can find any clues.

**Comment by davidzhao** [comment] 2022-04-08 16:55
`Incoming unhandled RTP ssrc` means a track could not be published properly. Can you provide more details on your use case? How are you using this? which client APIs are you using to publish? Which SDK/Device/Browser are you using on the client side and version.

For there to be any progress to be made on issues, we need as much information as you can provide.

**Comment by CensorKao** [comment] 2022-04-08 17:17
> `Incoming unhandled RTP ssrc` means a track could not be published properly. Can you provide more details on your use case? How are you using this? which client APIs are you using to publish? Which SDK/Device/Browser are you using on the client side and version.
> 
> For there to be any progress to be made on issues, we need as much information as you can provide.

I complied livekit-server from source code and then daemonized  by supervisor.

./livekit-server --config ./conf/livekit.yaml --node-ip x.x.x.x >> ./logs/livekit-server.log 2>&1

livekit.yaml is uploaded in #587

Livekit-server 4475a028b6a820412160bdaf3db18053c937a794
client-sdk-android v0.9.1

**Comment by CensorKao** [comment] 2022-05-06 11:07
@davidzhao 

We finally found the problem because one network adapter of our server was configured with multiple IP addresses, so the IP was not the access IP when listening locally. How to configure listening on only one IP address?

udp        0      0 192.168.120.77:13540    0.0.0.0:*
udp        0      0 192.168.120.78:14316    0.0.0.0:*
udp        0      0 192.168.120.79:15790    0.0.0.0:*

**Comment by davidzhao** [comment] 2022-05-07 04:43
Are you using `use_external_ip` ? that should help ensure it's advertising a public IP.

you can also specify desired interfaces [here](https://github.com/livekit/livekit-server/blob/v0.15.7/config-sample.yaml#L66)

**Comment by CensorKao** [comment] 2022-05-07 06:09
> use_external_ip

use_external_ip doesn't solve my problem, My problem is that there are multiple public IP addresses on the same NIC. I don't want Livekit to be able to listen to other IP addresses. And don't put other IP in SDP either. Even if I set use_external_IP, LiveKit will listen for other IP and write other IP to SDP at the same time.

All public IP addresses are in the same NIC, so specify desired interfaces doesn't work.

Or you can think of it this way, there are multiple LiveKits running on the same server, and each LiveKit will have a public IP address. And all public IP addresses are on the same NIC. When SDP is generated, other Livekit IP addresses will also be written in, resulting in confusion.

**Comment by davidzhao** [comment] 2022-05-07 06:15
How would you ideally like to configure this? specify each IP address in LiveKit config? some sort of CIDR mask?

**Comment by CensorKao** [comment] 2022-05-07 06:18
> How would you ideally like to configure this? specify each IP address in LiveKit config? some sort of CIDR mask?

I've seen some projects that listen for 0.0.0.0 so that all IP addresses are accessible. If I have 3 public IP addresses on my server, now LiveKit will have 6 UDP ports in the SDP. If you listen for 0.0.0.0, there will only be two DUP ports in the SDP.

**Comment by CensorKao** [comment] 2022-05-07 06:32
> How would you ideally like to configure this? specify each IP address in LiveKit config? some sort of CIDR mask?

udp        0      0 103.126.161.177:11060   0.0.0.0:*                           193842/./bin/1_livekit
udp        0      0 103.126.161.177:11240   0.0.0.0:*                           193842/./bin/1_livekit
udp        0      0 103.126.161.164:15398   0.0.0.0:*                           193842/./bin/1_livekit
udp        0      0 103.126.161.164:15796   0.0.0.0:*                           193842/./bin/1_livekit 
udp        0      0 103.126.161.163:13337   0.0.0.0:*                           193842/./bin/1_livekit
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           193842/./bin/1_livekit
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           193842/./bin/1_livekit
udp        0      0 103.126.161.163:13699   0.0.0.0:* 							193842/./bin/1_livekit

1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq state UP group default qlen 1000
    link/ether 00:1a:35:22:21:5a brd ff:ff:ff:ff:ff:ff
    inet 103.126.161.163/25 brd 103.126.161.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet 103.126.161.164/25 brd 103.126.161.255 scope global secondary eth0:0
       valid_lft forever preferred_lft forever
    inet 103.126.161.177/25 brd 103.126.161.255 scope global secondary eth0:1
       valid_lft forever preferred_lft forever
    inet6 fe80::216:3eff:ff28:295a/64 scope link 
       valid_lft forever preferred_lft forever

According to the above information, I have three public IP addresses on the server. So Livekit creates six UDP ports. If LiveKit only listens for 0.0.0.0, then only two UDP ports are needed. In this way, there are not too many invalid ports in the SDP.

**Comment by davidzhao** [comment] 2022-09-29 06:45
This has been fixed in #1052

**Closed by davidzhao** 2022-09-29 06:45 UTC
