### ISSUE TITLE
Regression: video is not visible as fast as before (1.0.0 vs 0.15.7)

### ISSUE THREAD

**Issue by gabjauf** [livekit/livekit#712] opened 2022-05-24 10:42 UTC
**Describe the bug**
The title may not be that clear, feel free to rename it 🙃 

Context: One publisher to many subscribers

I thought at first that it was a client issue but it turns out that changing the livekit server version deployed changed the behavior.

Using the same client code (livekit-client-sdk), I get the image and sound faster with server version 0.15.7 while the 1.0.0 is taking quite a long time (a few seconds) without displaying.

**Server**
- Version: 1.0.0
- Environment: docker-compose deployment on AWS ubuntu with cloud init
- Just changed the version of the container in docker-compose 

**Client**
- SDK: js
- Version: [0.18.5, 1.0.0]
- Browsers: Brave, Chromium, Safari
- rtcConfig: {
     iceTransportPolicy: 'relay',
   },
- codec: h264
- simulcast: false

**To Reproduce**
1. Publisher connects to room in publish_only
2. Subscriber connects to room
3. In 0.15.7, the image displays directly (sometimes with a click, like on chrome). In 1.0.0, the image displays only after a few seconds, even with a click (variable but usually 15 to 30 seconds)

**Expected behavior**
1.0.0 version should match the 0.15.7 behavior.

**Comment by gabjauf** [comment] 2022-05-24 10:45
Available for more details on the issue 😉

**Comment by boks1971** [comment] 2022-05-24 11:10
@gabjauf Are you using `adaptiveStream`. In v1.0.0 of server, video is not sent by server till the subscription update is received by the server. Is the client sending subscription update as soon as the subscriber joins?

 Is the audio available immediately or is it also taking 15 to 30 seconds?

**Comment by gabjauf** [comment] 2022-05-24 11:21
Not using adaptiveStream (it is off by default if the docs are up to date)
Audio is not available right away.
It seems like the server is not sending any data for a while:

Publisher:
<img width="1618" alt="Capture d’écran 2022-05-24 à 13 18 37" src="https://user-images.githubusercontent.com/17923230/170022973-3d12a0a9-3551-4f21-8f91-f76abd8d0faf.png">

Subscriber:
<img width="1781" alt="Capture d’écran 2022-05-24 à 13 18 28" src="https://user-images.githubusercontent.com/17923230/170022957-5c664427-52ce-468e-814f-1ea9708c426b.png">

Notice the almost 2minutes gap between publisher started video and subscriber started receiving the frames

**Comment by gabjauf** [comment] 2022-05-24 11:35
No change, I just change the livekit server versions in docker-compose file and it changes the behavior.

**Comment by davidzhao** [comment] 2022-07-21 21:55
there's nothing that could explain a 2 minute gap. if you can reproduce this, please provide steps to reproduce this issue. How are you publishing video into livekit?

**Comment by gabjauf** [comment] 2022-07-27 13:56
The video is published from the browser with the front camera of a computer or phone.

I will try to provide a bit more info so you can reproduce but I am a bit out of time right now 😓

**Comment by davidzhao** [comment] 2022-09-19 06:52
Closing as we cannot reproduce. Please re-open with specific steps to repro if this remains an issue.

**Closed by davidzhao** 2022-09-19 06:52 UTC
