### ISSUE TITLE
System.InvalidOperationException: DataChannel is not open when sending my data(Unity)

### ISSUE THREAD

**Issue by tisaud** [livekit/livekit#1461] opened 2023-02-23 12:24 UTC
System.InvalidOperationException: DataChannel is not open when sending my data(Unity)

**Server**

**Client**
use this unity case 
https://github.com/maxstdev/livekit-client-sdk-unity-native

show my code 
![error2](https://user-images.githubusercontent.com/33447003/220904629-0d751662-f259-46db-80b0-c20c614aea24.png)
my concole errors
![error1](https://user-images.githubusercontent.com/33447003/220904691-af926587-0d4d-43de-b14b-df0b8390c47e.png)

I wonder if there are any settings that have been overlooked to cause this problem, maybe the server or the client

**Comment by davidzhao** [comment] 2023-02-25 07:47
Wow! this is really awesome what you've built this SDK!

I think the reason for the error is [here](https://github.com/maxstdev/livekit-client-sdk-unity-native/blob/main/Runtime/Scripts/Core/Engine.cs#L297). where the data channel opens *after* the publisher connection has connected. 

You should wait until readyState is flipped to `open` before publishing. [here's](https://github.com/livekit/client-sdk-js/blob/main/src/room/RTCEngine.ts#L987) an example of how we handle it in JS SDK.

Closing this issue here because it's not a bug with livekit itself. If you have any further questions, you are welcome to join our [Slack channel](https://join.slack.com/t/livekit-users/shared_invite/zt-rrdy5abr-5pZ1wW8pXEkiQxBzFiXPUg)

**Closed by davidzhao** 2023-02-25 07:47 UTC
