### ISSUE TITLE
High quality audio issue

### ISSUE THREAD

**Issue by Naznow** [livekit/livekit#2101] opened 2023-09-24 06:20 UTC
right now i am using android SDK but audio quality is not good.
how can i get mp3 quality level audio.
is there any way to get same to same as music level audio so user can play music and talk both at a time.

my config is here

> val options = RoomOptions(
audioTrackCaptureDefaults = LocalAudioTrackOptions(
noiseSuppression = false,
echoCancellation = false,
autoGainControl = false,
highPassFilter = false,
typingNoiseDetection = false,
),
videoTrackCaptureDefaults = LocalVideoTrackOptions(
deviceId = "",
position = CameraPosition.FRONT,
captureParams = VideoPreset169.HD.capture,
),
audioTrackPublishDefaults = AudioTrackPublishDefaults(
audioBitrate = 128_000,
dtx = false,
),

**Comment by davidzhao** [comment] 2023-09-24 06:23
dupe of https://github.com/livekit/client-sdk-android/issues/259

**Closed by davidzhao** 2023-09-24 06:23 UTC
