### ISSUE TITLE
A screenShare track appears as a camera track

### ISSUE THREAD

**Issue by burzomir** [livekit/livekit#1603] opened 2023-04-12 11:33 UTC
**Describe the bug**
Publication of screenShare and screenShareAudio fails when main JS thread is overwhelmed (slower computers + complex logic at time of publication). LocalParticipant receives track publication success. In the server logs there is track publication timeout reported by supervisor. Other participants may see screenShare track content transmitted along the camera track. 

**Server**
meet.livekit.io

**Client**
latest client-js
https://livekit-test.burzomir.repl.co

**To Reproduce**

1. Go to https://meet.livekit.io/, login to demo as participant1 and copy URL
2. Open new tab in Chrome, open devtools network tab, filter by WS, and open previously copied URL
3. Login to demo as participant2, copy wss url and token from network tab's livekit connection entry
4. Open example app https://livekit-test.burzomir.repl.co, paste wss url and token
5. Click join
6. Click start camera
7. Check `freeze main thread after publication` checkbox
8. Click start screen and share tab with sound (e.g. youtube video)

**Expected behavior**
LocalParticipant is informed about screen share publication failure so that he can try to publish it again.

**Screenshots**
Attached video in steps to reproduce section in https://livekit-test.burzomir.repl.co

**Additional context**
The same supervisor timeout errors appear in logs for this issue: https://github.com/livekit/livekit/issues/1238

**Comment by cnderrauber** [comment] 2023-04-14 07:59
It is caused by pion parse stream id incorrectly when the offer SDP has more than one simulcast transceivers, fixed in  PR(https://github.com/pion/webrtc/pull/2455) and will release in next version.

**Closed** 2023-04-17 02:41 UTC
